#+title: CUSTOMIZATIONS

Customizable variables

* meow-mode-state-list

Default:

#+begin_src emacs-lisp
  ((fundamental-mode . normal)
   (text-mode . normal)
   (prog-mode . normal)
   (conf-mode . normal)
   (json-mode . normal)
   ...)
#+end_src

A list of rules to specify the initial Meow state for major mode.

Value should be a list, each item is ~(major-mode . init-state)~.
The ~init-state~ can only be ~motion~ or ~normal~.

By Default, Meow will use ~motion~ for special modes, and ~normal~ for other modes.

* meow-expand-exclude-mode-list

Default: ~(markdown-mode org-mode)~

A list of major modes where expand feature should be disabled.

The expand feature use ~overlay~ for display,
and it may not work well with texts with inconsistent sizes.

* meow-selection-command-fallback

Default:
#+begin_src emacs-lisp
  ((meow-change . meow-change-char)
   (meow-kill . meow-C-k)
   (meow-cancel-selection . keyboard-quit)
   (meow-pop-selection . meow-pop-grab))
#+end_src

Fallback behaviours for selection-only commands when there's no selection.

* meow-keypad-message

Default: ~t~

Whether to log keypad messages in minibuffer.

* meow-char-thing-table

Default:
#+begin_src emacs-lisp
  ((?r . round)
   (?s . square)
   (?c . curly)
   (?g . string)
   (?e . symbol)
   (?w . window)
   (?b . buffer)
   (?p . paragraph)
   (?l . line)
   (?d . defun)
   (?i . indent)
   (?x . extend))
#+end_src

Mapping from char to thing.

Used by ~meow-beginning-of-thing~, ~meow-end-of-thing~, ~meow-inner-of-thing~ and ~meow-bounds-of-thing~.

* meow-replace-state-name-list

Default:
#+begin_src emacs-lisp
  ((normal . "NORMAL")
   (motion . "MOTION")
   (keypad . "KEYPAD")
   (insert . "INSERT")
   (bmacro . "BMACRO"))
#+end_src

A list of mappings for how state is displayed in modeline indicator.

* meow-display-thing-help

Default: ~t~

Whether to display the help prompt for ~meow-inner/bounds/begin/end-of-thing~.

* meow-keypad-describe-delay

Default: ~0.5~

The delay in seconds before popup keybinding descriptions appear.

* meow-grab-fill-commands

Default: ~(meow-query-replace meow-query-replace-regexp)~

A list of commands that meow will auto fill with grabbed content.

* meow-visit-collect-min-length

Default: ~1~

Minimal length when collecting symbols for ~meow-visit~.

* meow-visit-sanitize-completion

Default: ~t~

Whether let ~meow-visit~ display symbol regexps in a sanitized format.

* meow-use-clipboard

Default: ~nil~

Whether to use system clipboard. Not recommended.

* meow-use-keypad-when-execute-kbd

Default: ~t~

Whether to use KEYPAD when the result of executing kbd string is a keymap.

* meow-keypad-meta-prefix

Default: ~?m~

The prefix represent M- in KEYPAD state.

* meow-keypad-ctrl-meta-prefix

Default: ~?g~

The prefix represent C-M- in KEYPAD state.

* meow-keypad-literal-prefix

Default: ~32~ (SPC character)

The prefix represent no modifier in KEYPAD state.

* meow-expand-selection-type

Default: ~select~

The type of selection activated by ~meow-expand-*~ commands.
