#+title: FREQUENTLY ASKED QUESTIONS

* Why do meow-append and meow-insert behave the same way when there is no region?

In Emacs cursor is located between two characters, so we would have to implement a hack to change the behaviour. You can read more about it in [[https://github.com/meow-edit/meow/discussions/87][this discussion thread]].

* How to customize the +prefix menus in Keypad mode?

Please check [[https://github.com/meow-edit/meow/issues/71#issuecomment-962090002][This issue]].

* I encountered a weird command behavior in normal state

Meow's internal command will not call Emacs' commands directly. They will call a keybind which is then linked to a command.  Your customized keybind might be overriding the original command. Lookup the command you want to execute ([[meow-var.el][meow-var.el]]) and overwrite it in your config.

[[https://github.com/meow-edit/meow/issues/109][Related issue]]

Example:

Here you can map Delete character to internal Meow's delete character function.
#+begin_src emacs-lisp
  (setq meow--kbd-delete-char "<deletechar>")
#+end_src

The keyboard macro variables can also be assigned to defuns if you don't want them to correspond to a keyboard macro.

Example:
#+BEGIN_SRC emacs-lisp
  (setq meow--kbd-forward-line #'next-line)
#+END_SRC


* Is there a integration with treesit?

Yes, please check out [[https://github.com/skissue/meow-tree-sitter][meow-tree-sitter]].

* Can I use meow in doom-emacs?

Yes, please check out [[https://github.com/meow-edit/doom-meow][doom meow module]].

* Can I have a major-mode specified local leader?

No, you can't.  Here is [[https://github.com/meow-edit/meow/pull/126#issuecomment-992004368][the explanation]].

* Why don't the number hints for extending selection show up in org-mode buffers?

The extend selection number hints are disabled in org-mode by default, because they work poorly with variable-width fonts, and fonts with different sizes. If you use a fixed width font and a single font size, the number hints can be enabled in org mode by removing the org symbol from the list meow-expand-exclude-mode-list . See [[https://github.com/meow-edit/meow/issues/110][this issue for more details]].
