#+title: GET STARTED

* Dependencies

Emacs >= 27.2

* Installation
Meow is available on [[https://melpa.org/#/meow][Melpa]], you can install it with your favorite package manager.

*** Try without installation
If you want to give it a try without touching your configuration.

#+begin_src sh
  git clone https://github.com/meow-edit/meow.git /path/to/meow
  cd /path/to/meow
  emacs -q -L . -l meow.el
#+end_src

Continue with the next steps.

* Set up command layout
Meow has no default command layout.
You can write your own setup function from scratch or pick one from below as your starting point.

- [[file:KEYBINDING_QWERTY.org][Qwerty layout]]
- [[file:KEYBINDING_DVORAK.org][Dvorak layout]]
- [[file:KEYBINDING_DVP.org][Programmer Dvorak layout]]
- [[file:KEYBINDING_COLEMAK.org][Colemak layout]]

* Enable meow globally
Add the following code to your configuration.
#+begin_src emacs-lisp
  <define your meow-setup>
  (require 'meow)
  (meow-setup)
  (meow-global-mode 1)
#+end_src

* Tutorial in Emacs
Now you can open the tutorial with ~M-x meow-tutor~.

* Cheatsheet
If everything works as expected, now you can open the cheatsheet with ~SPC ?~.

The keyboard layout in the cheatsheet is customizable. By default, it's the ANSI layout, but the ISO layout is also supported.
#+begin_src emacs-lisp
(setq meow-cheatsheet-physical-layout meow-cheatsheet-physical-layout-ansi)
#+end_src
